topic_prefix: pi/io
mqtt_server_ip: localhost
mqtt_server_port: 1883
mqtt_server_user: mqtt
mqtt_server_password: 123abc

latitude: 56
longitude: 10

pump: revpi/io/heat_pump/set

rooms:
  office:
    sensors:
      - zigbee2mqtt/office/temp_sensor
    output_heat_topic: revpi/io/office/heat/set