version: '3.6'
services:
  mqttio:
    build: 
      context: .
    privileged: true
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.yml:/config.yml
      - /etc/revpi/config.rsc:/config.rsc

